---
namespace: suitenumerique
name: st
readme: README.md
authors:
  - La Suite Territoriale
license_file: "LICENSE"
repository: https://github.com/suitenumerique/st-ansible
issues: https://github.com/suitenumerique/st-ansible/issues
documentation: https://github.com/suitenumerique/st-ansible
homepage: https://suiteterritoriale.anct.gouv.fr/
tags: ["suitenumerique", "suiteterritoriale", "linux"]
version: 0.0.1
description: Installe, configure et pilote les composants de La Suite Territoriale sur des systèmes Debian.
dependencies: {}
build_ignore:
  - .gitignore
  - .ansible-lint
  - build
