---
- name: "Import Suite Territoriale podman role."
  ansible.builtin.import_role:
    name: suitenumerique.st.podman
  vars:
    st_podman_user: "messages"
    st_podman_uid: "{{ st_messages_uid }}"
    st_podman_gid: "{{ st_messages_gid }}"
    st_podman_registries: "{{ st_messages_registries | default([]) }}"
