---
- name: "Create cadvisor application."
  ansible.builtin.import_role:
    name: suitenumerique.st.podman
    tasks_from: application.yml
  vars:
    st_podman_user: "messages"
    st_podman_application_name: "cadvisor"
    st_podman_application_compose_template: monitoring/compose_cadvisor.yaml.j2

- name: "Import Suite Territoriale alloy role."
  when: st_messages_monitoring_enabled
  tags: ['messages_monitoring']
  ansible.builtin.import_role:
    name: suitenumerique.st.alloy
  vars:
    st_alloy_config_template: "monitoring/config.alloy.j2"
