---
# Don't specify permissions and owner here because it's get owned by the unbound user subuid inside the container
# - { src: "{{ st_messages_mpa_unbound_config_template }}", dest: unbound_config/unbound.conf, mode: omit, dir_mode: omit }

- name: "Setup default mpa configuration templates."
  ansible.builtin.set_fact:
    mpa_base_files:
      - { src: mpa/rspamd/worker-controller.inc.j2, dest: rspamd_config/override.d/worker-controller.inc, mode: "0644", dir_mode: "0755" }
      - { src: mpa/rspamd/worker-proxy.inc.j2, dest: rspamd_config/override.d/worker-proxy.inc, mode: "0644", dir_mode: "0755" }
      - { src: mpa/rspamd/options.inc.j2, dest: rspamd_config/local.d/options.inc, mode: "0644", dir_mode: "0755" }
      - { src: mpa/rspamd/logging.inc.j2, dest: rspamd_config/local.d/logging.inc, mode: "0644", dir_mode: "0755" }
      - { src: mpa/rspamd/antivirus.conf.j2, dest: rspamd_config/local.d/antivirus.conf, mode: "0644", dir_mode: "0755" }
      - { src: mpa/rspamd/multimap.conf.j2, dest: rspamd_config/local.d/multimap.conf, mode: "0644", dir_mode: "0755" }
      - { src: mpa/rspamd/history_redis.conf.j2, dest: rspamd_config/local.d/history_redis.conf, mode: "0644", dir_mode: "0755" }
      - { src: "{{ st_messages_mpa_clamav_config_template }}", dest: clamav_config/clamd.conf, mode: "0644", dir_mode: "0755" }
      - { src: "mpa/rspamd/redis.conf.j2", dest: rspamd_config/local.d/redis.conf, mode: "0644", dir_mode: "0755", when: st_messages_mpa_valkey_enabled }
      - { src: "mpa/nginx.conf.j2", dest: nginx_config/nginx.conf, when: st_messages_mpa_auth_bearer is defined and st_messages_mpa_auth_bearer | length > 0 }

- name: "Create mpa app"
  ansible.builtin.import_role:
    name: suitenumerique.st.podman
    tasks_from: application.yml
  vars:
    st_podman_user: "messages"
    st_podman_application_name: "mpa"
    st_podman_application_compose_template: "{{ st_messages_mpa_compose_template }}"
    st_podman_application_files: "{{ mpa_base_files | community.general.lists_mergeby(st_messages_mpa_rspamd_config_templates, 'dest') }}"
