---
- name: "Create mta-in application."
  ansible.builtin.import_role:
    name: suitenumerique.st.podman
    tasks_from: application.yml
  vars:
    st_podman_user: "messages"
    st_podman_application_name: "mta-in"
    st_podman_application_compose_template: "{{ st_messages_mta_in_compose_template }}"
    st_podman_application_files:
      - src: "{{ st_messages_mta_in_env_template }}"
        dest: "env"
