---
- name: "Create messages workers application."
  ansible.builtin.import_role:
    name: suitenumerique.st.podman
    tasks_from: application.yml
  vars:
    st_podman_user: "messages"
    st_podman_application_name: "workers"
    st_podman_application_dir: "{{ st_messages_workers_dir }}"
    st_podman_application_rollback_enabled: "{{ st_messages_workers_rollback_enabled }}"
    st_podman_application_compose_template: "{{ st_messages_workers_compose_template }}"
    st_podman_application_files:
      - src: "{{ st_messages_workers_env_template }}"
        dest: "env"
