---
- name: "Deploy livekit."
  hosts: livekit
  tasks:
    - name: "Install meet base."
      become: true
      become_user: root
      ansible.builtin.import_role:
        name: suitenumerique.st.meet

    - name: "Deploy livekit application."
      become: true
      become_user: meet
      become_method: ansible.builtin.sudo
      become_flags: "-i"
      ansible.builtin.import_role:
        name: suitenumerique.st.meet
        tasks_from: deploy.yml
      vars:
        st_meet_livekit_enabled: true
        st_meet_cadvisor_enabled: true
        st_meet_livekit_rollback_enabled: "{{ true if inventory_hostname == ansible_play_hosts_all[0] else false }}"
        st_meet_livekit_tag: vx.y.z # check https://hub.docker.com/r/livekit/livekit-server/tags
        st_meet_livekit_egress_tag: vx.y.z # check https://hub.docker.com/r/livekit/egress/tags
        st_meet_livekit_valkey_tag: x.y.z # check https://hub.docker.com/r/valkey/valkey/tags
        st_meet_livekit_caddy_version: vx.y.z # check https://github.com/caddyserver/caddy/releases

        st_meet_livekit_domain: livekit.suite.anct.gouv.fr
        st_meet_livekit_turn_domain: livekit-turn.suite.anct.gouv.fr
        st_meet_livekit_api_key: "{{ vault_livekit_api_key }}"
        st_meet_livekit_api_secret: "{{ vault_livekit_api_secret }}"

        st_meet_livekit_compose_template: "compose.yaml.j2"
        st_meet_livekit_directories:
          - { name: caddy }

        st_meet_livekit_files:
          - { src: "livekit.yaml.j2", dest: livekit.yaml }
          - { src: "caddy.json.j2", dest: caddy/caddy.json }
          - { src: "Dockerfile.caddy.j2", dest: caddy/Dockerfile }

        # templates variables
        redis_host: "10.0.0.243:6379"
        redis_username: "{{ vault_redis_username }}"
        redis_password: "{{ vault_redis_password }}"
        scaleway_secret_key: "{{ vault_scaleway_secret_key }}"
        scaleway_organisation_id: "xxx"

        public_interface: "ens2"
        public_ip: "{{ hostvars[inventory_hostname]['ansible_' + public_interface].ipv4.address }}"
