---
dependency:
  name: galaxy

driver:
  name: molecule-lima

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks,timer
      host_key_checking: false

verifier:
  name: ansible

platforms:
  - name: instance
