---
- name: "Configure restic-alert systemd unit and script."
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { src: alert.service.j2, dest: /etc/systemd/system/restic-alert.service, mode: "0644" }
    - { src: alert.sh.j2, dest: /usr/local/bin/restic-alert.sh, mode: "0700" }
  notify: "systemctl daemon-reload"

- name: "Ensure systemctl daemon-reload."
  ansible.builtin.meta: flush_handlers
