---
- name: "Ensure {{ st_valkey_instance_name }} instance config directory."
  ansible.builtin.file:
    name: "{{ st_valkey_instance_config_dir }}"
    owner: "stvalkey"
    group: "stvalkey"
    mode: "0750"
    state: directory

- name: "Check if {{ st_valkey_instance_name }} valkey instance configuration needs init."
  ansible.builtin.stat:
    name: "{{ st_valkey_instance_config_dir }}/valkey.conf"
  register: instance_config

- name: "Initialize {{ st_valkey_instance_name }} valkey instance configuration."
  when: not instance_config.stat.exists
  ansible.builtin.template:
    src: instance/valkey.skel.j2
    dest: "{{ st_valkey_instance_config_dir }}/valkey.conf"
    owner: "stvalkey"
    group: "stvalkey"
    mode: "0600"

- name: "Deploy {{ st_valkey_instance_name }} valkey instance configuration."
  ansible.builtin.blockinfile:
    path: "{{ st_valkey_instance_config_dir }}/valkey.conf"
    block: "{{ lookup('template', st_valkey_instance_config_template) }}"
    owner: "stvalkey"
    group: "stvalkey"
    mode: "0600"
  notify: "systemctl --user restart {{ st_valkey_instance_name }}"

- name: "Deploy {{ st_valkey_instance_name }} valkey instance ACL file."
  ansible.builtin.template:
    src: "{{ st_valkey_instance_users_template }}"
    dest: "{{ st_valkey_instance_config_dir }}/users.acl"
    owner: "stvalkey"
    group: "stvalkey"
    mode: "0600"
  notify: "systemctl --user restart {{ st_valkey_instance_name }}"

- name: "Create {{ st_valkey_instance_name }} valkey instance."
  ansible.builtin.import_role:
    name: suitenumerique.st.podman
    tasks_from: application.yml
  vars:
    st_podman_user: "stvalkey"
    st_podman_home: "/opt/valkey"
    st_podman_application_name: "{{ st_valkey_instance_name }}"
    st_podman_application_compose_template: "{{ st_valkey_instance_compose_template }}"
