---
- name: "Set sysctl vm.overcommit_memory."
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: "1"
    sysctl_set: true
    sysctl_file: "/etc/sysctl.d/99-valkey.conf"
    state: present

- name: "Deploy systemd unit to disable THP."
  ansible.builtin.template:
    src: disable_thp.service.j2
    dest: /etc/systemd/system/disable_thp.service
    owner: root
    group: root
    mode: "0640"
  notify:
    - "systemctl daemon-reload"
    - "systemctl start disable_thp"

- name: "Flush handlers."
  ansible.builtin.meta: flush_handlers

- name: "Ensure disable_thp systemd unit is enabled."
  ansible.builtin.systemd_service:
    name: "disable_thp"
    enabled: true
