---
# Note: ce rôle n'initialise pas la première réplication dans le cas d'une nouvelle install.
# Pour le faire, il suffit de se connecter à la cli d'un slave fraichement déployé et de lancer la commande suivante :
#      replicaof ip_master port_master
#
- name: "Import kernel.yml"
  ansible.builtin.import_tasks: kernel.yml
  tags: ['valkey_kernel']

- name: "Import sentinel/install.yml"
  ansible.builtin.import_tasks: sentinel/install.yml
  tags: ['valkey_sentinel_install']

- name: "Import sentinel/service.yml"
  ansible.builtin.import_tasks: sentinel/service.yml
  tags: ['valkey_sentinel_service']

- name: "Import sentinel/config.yml"
  ansible.builtin.import_tasks: sentinel/config.yml
  tags: ['valkey_sentinel_config']

- name: "Import Suite Territoriale podman role."
  ansible.builtin.import_role:
    name: suitenumerique.st.podman
  vars:
    st_podman_user: "stvalkey"
    st_podman_home: "/opt/valkey"
