---
- name: Create Lima instances
  hosts: localhost
  gather_facts: false
  vars:
    ssh_timeout: "{{ molecule_yml.driver.ssh_timeout | default(120) }}"

  tasks:
    - name: Validate Lima is installed
      ansible.builtin.command: limactl --version
      register: lima_version
      changed_when: false
      failed_when: lima_version.rc != 0

    - name: Create Lima instances
      ansible.builtin.include_tasks: tasks/create_instance.yml
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        loop_var: instance

    - name: Dump instance config
      ansible.builtin.copy:
        content: "{{ instance_config_data | to_yaml }}"
        dest: "{{ molecule_ephemeral_directory }}/instance_config.yml"
        mode: '0600'
      delegate_to: localhost
      run_once: true

- name: Validate instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait for instances to be ready
      ansible.builtin.include_tasks: tasks/validate_instance.yml
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        loop_var: instance
