---
- name: "Clean up {{ st_podman_application_name }} application rollback directory."
  when: st_podman_application_rollback_enabled
  ansible.builtin.file:
    path: "{{ st_podman_application_dir }}.rollback"
    state: absent

- name: "Check if {{ st_podman_application_name }} application directory exists for backup."
  when: st_podman_application_rollback_enabled
  ansible.builtin.stat:
    path: "{{ st_podman_application_dir }}"
  register: app_dir_stat

# INFO: We use `cp` here because the copy module breaks ownership in every case
- name: "Backup {{ st_podman_application_name }} application directory for potential rollback."
  when: st_podman_application_rollback_enabled and app_dir_stat.stat.exists
  ansible.builtin.command:
    cmd: "cp -a {{ st_podman_application_dir }}/. {{ st_podman_application_dir }}.rollback/"
  changed_when: true

- name: "Deploy {{ st_podman_application_name }} application systemd unit."
  ansible.builtin.template:
    src: "application_systemd_unit.j2"
    dest: "{{ st_podman_home }}/.config/systemd/user/{{ st_podman_application_name }}.service"
    owner: "{{ st_podman_user }}"
    group: "{{ st_podman_group }}"
    mode: "0600"
  notify:
    - "systemctl --user daemon-reload {{ st_podman_application_name }}"
    - "systemctl --user restart {{ st_podman_application_name }}"

- name: "Deploy {{ st_podman_application_name }} application systemd ExecStart script."
  ansible.builtin.copy:
    src: "application_execstart.sh"
    dest: "{{ st_podman_home }}/.config/systemd/user/{{ st_podman_application_name }}.sh"
    owner: "{{ st_podman_user }}"
    group: "{{ st_podman_group }}"
    mode: "0700"
  notify:
    - "systemctl --user restart {{ st_podman_application_name }}"

- name: "Ensure {{ st_podman_application_name }} application directory."
  ansible.builtin.file:
    name: "{{ st_podman_application_dir }}"
    owner: "{{ st_podman_user }}"
    group: "{{ st_podman_group }}"
    mode: "{{ st_podman_application_dir_mode }}"
    state: directory

- name: "Deploy and start {{ st_podman_application_name }}."
  become: true
  become_user: "{{ st_podman_user }}"
  become_method: ansible.builtin.sudo
  become_flags: "-i"
  block:
    # INFO:
    #  - we want some files (env files, config files...) to be accessible by a subuid inside the container
    #  - Linux does not really care if the subuid belongs to you when checking the permissions -
    #    that means everything kind of breaks for st_podman_user if the file is only accessible by the subuid
    # In the end what we do is :
    #  - Deploy everything as 2770 or 0660
    #  - If no container_uid →  owner and group set to st_podman_user
    #  - If container_uid →  owner set to container_uid with `podman unshare`, group stays to st_podman_user (2770/0660 makes it so it doesn't break)
    #  - The user can still change container_gid if he knows what he's doing, **but it will probably break stuff**
    - name: "Ensure {{ st_podman_application_name }} application directories"
      ansible.builtin.include_tasks: application/directories.yml
      loop: "{{ st_podman_application_directories }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - st_podman_application_directories is defined
        - st_podman_application_directories | length > 0
        - item.when | default(true)

    - name: "Ensure {{ st_podman_application_name }} application files"
      ansible.builtin.include_tasks: application/files.yml
      loop: "{{ st_podman_application_files }}"
      loop_control:
        label: "{{ item.dest }}"
      when:
        - st_podman_application_files is defined
        - st_podman_application_files | length > 0
        - item.when | default(true)

    - name: "Deploy {{ st_podman_application_name }} application compose file."
      ansible.builtin.template:
        src: "{{ st_podman_application_compose_template }}"
        dest: "{{ st_podman_application_dir }}/compose.yaml"
        owner: "{{ st_podman_user }}"
        group: "{{ st_podman_group }}"
        mode: "0600"
      notify:
        - "systemctl --user restart {{ st_podman_application_name }}"

    - name: "Ensure {{ st_podman_application_name }} application copied files"
      ansible.builtin.include_tasks: application/copy_files.yml
      loop: "{{ st_podman_application_copy_files }}"
      loop_control:
        label: "{{ item.dest }}"
      when:
        - st_podman_application_copy_files is defined
        - st_podman_application_copy_files | length > 0
        - item.when | default(true)

    - name: "Flush handlers."
      ansible.builtin.meta: flush_handlers

    - name: "Ensure {{ st_podman_application_name }} application is started and enabled."
      ansible.builtin.systemd_service:
        name: "{{ st_podman_application_name }}"
        state: started
        enabled: true
        scope: user

    # INFO: This will only runs if the deploy works.
    - name: "Clean up {{ st_podman_application_name }} application rollback directory."
      when: st_podman_application_rollback_enabled
      ansible.builtin.file:
        path: "{{ st_podman_application_dir }}.rollback"
        state: absent

  rescue:
    - name: "Perform rollback on {{ st_podman_application_name }}."
      become: true
      become_user: "{{ st_podman_user }}"
      become_method: ansible.builtin.sudo
      become_flags: "-i"
      when: st_podman_application_rollback_enabled
      block:
        - name: "ROLLBACK | Remove broken application directory."
          ansible.builtin.file:
            path: "{{ st_podman_application_dir }}"
            state: absent

        - name: "ROLLBACK | Restore {{ st_podman_application_name }} directory from rollback."
          ansible.builtin.command:
            cmd: "mv {{ st_podman_application_dir }}.rollback {{ st_podman_application_dir }}"
          changed_when: true

        # INFO: We can't use the handlers here because if any task fails,
        # Ansible stops the execution on the host, and doesn't run the handlers.
        - name: "ROLLBACK | systemctl --user restart {{ st_podman_application_name }}"
          ansible.builtin.systemd_service:
            name: "{{ st_podman_application_name }}"
            state: restarted
            scope: user

    - name: "Fail deployment."
      ansible.builtin.fail:
        msg: >-
          {{ "Deployment failed, rollback performed."
             if st_podman_application_rollback_enabled
             else "Deployment failed, no rollback performed as it is disabled." }}
