---
- name: "Ensure podman.socket is started and enabled."
  become: true
  become_user: "{{ st_podman_user }}"
  become_method: ansible.builtin.sudo
  become_flags: "-i"
  ansible.builtin.systemd_service:
    name: "podman.socket"
    state: started
    enabled: true
    scope: user
