---
- name: "Ensure {{ st_podman_group }} group is present."
  ansible.builtin.group:
    name: "{{ st_podman_group }}"
    gid: "{{ st_podman_gid | default(omit) }}"

- name: "Ensure {{ st_podman_user }} user is present."
  ansible.builtin.user:
    name: "{{ st_podman_user }}"
    group: "{{ st_podman_group }}"
    home: "{{ st_podman_home }}"
    uid: "{{ st_podman_uid | default(omit) }}"
    shell: "/bin/bash"
    create_home: true
    password_lock: true

- name: "Ensure {{ st_podman_user }} user home config directories."
  ansible.builtin.file:
    name: "{{ item }}"
    owner: "{{ st_podman_user }}"
    group: "{{ st_podman_group }}"
    mode: "0750"
    state: directory
  loop:
    - "{{ st_podman_home }}"
    - "{{ st_podman_home }}/.config/containers"
    - "{{ st_podman_home }}/.config/systemd/user"

- name: "Ensure {{ st_podman_user }} user home config files."
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ st_podman_user }}"
    group: "{{ st_podman_group }}"
    mode: "0640"
  loop:
    - { src: bash_profile.j2, dest: "{{ st_podman_home }}/.bash_profile" }
    - { src: "{{ st_podman_containers_config_template }}", dest: "{{ st_podman_home }}/.config/containers/containers.conf" }

- name: "Ensure lingering is enabled for {{ st_podman_user }} user."
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ st_podman_user }}"
    creates: "/var/lib/systemd/linger/{{ st_podman_user }}"

- name: "Ensure {{ st_podman_user }} podman.socket is started and enabled."
  become: true
  become_user: "{{ st_podman_user }}"
  become_method: ansible.builtin.sudo
  become_flags: "-i"
  ansible.builtin.systemd_service:
    name: "podman.socket"
    state: started
    enabled: true
    scope: user
