---
- name: "Ensure collabora application directory."
  ansible.builtin.file:
    name: "/opt/drive/collabora"
    owner: "drive"
    group: "drive"
    mode: "0750"
    state: directory

- name: "Deploy collabora env file."
  ansible.builtin.template:
    src: "{{ st_drive_collabora_env_template }}"
    dest: "/opt/drive/collabora/env"
    owner: "drive"
    group: "drive"
    mode: "0600"
  notify: "systemctl --user restart collabora"

- name: "Create collabora application."
  ansible.builtin.import_role:
    name: suitenumerique.st.podman
    tasks_from: application.yml
  vars:
    st_podman_user: "drive"
    st_podman_application_name: "collabora"
    st_podman_application_compose_template: collabora/compose.yaml.j2
