---
- name: "Create drive application."
  ansible.builtin.import_role:
    name: suitenumerique.st.podman
    tasks_from: application.yml
  vars:
    st_podman_user: "drive"
    st_podman_application_name: "drive"
    st_podman_application_dir: "{{ st_drive_dir }}"
    st_podman_application_rollback_enabled: "{{ st_drive_rollback_enabled }}"
    st_podman_application_compose_template: "{{ st_drive_compose_template }}"
    st_podman_application_files:
      - src: "{{ st_drive_backend_env_template }}"
        dest: "backend_env"
      - src: "{{ st_drive_frontend_env_template }}"
        dest: "frontend_env"
      - src: "{{ st_drive_nginx_template }}"
        dest: "nginx.conf"
        mode: "0644"

- name: "Play drive migrations."
  become: true
  become_user: "drive"
  become_method: ansible.builtin.sudo
  become_flags: "-i"
  run_once: true
  register: migration_result
  changed_when: "'No migrations to apply.' not in migration_result.stdout"
  when: st_drive_backend_run_migrations
  retries: 3
  delay: 10
  until: migration_result.rc == 0
  ansible.builtin.shell:
    chdir: "{{ st_drive_dir }}"
    cmd: |
      set -eu
      podman-compose run --rm --name drive_backend_migrations backend python manage.py migrate --noinput
