---
- name: "Valkey Failover playbook."
  hosts: "{{ targets | default('valkey') }}"
  run_once: true
  tasks:
    - name: "Get old primary."
      changed_when: true
      register: oldprimary
      ansible.builtin.shell: |
        set -eu
        valkey-cli -p {{ st_valkey_sentinel_port | default('26379') }} -e sentinel get-primary-addr-by-name {{ primary_name }}

    - name: "Execute failover"
      changed_when: true
      register: failover
      ansible.builtin.shell: |
        set -eu
        valkey-cli -p {{ st_valkey_sentinel_port | default('26379') }} -e sentinel ckquorum {{ primary_name }}
        valkey-cli -p {{ st_valkey_sentinel_port | default('26379') }} -e sentinel failover {{ primary_name }}

    - name: "Wait for new primary."
      changed_when: true
      register: newprimary
      ansible.builtin.shell: |
        set -eu
        valkey-cli -p {{ st_valkey_sentinel_port | default('26379') }} -e sentinel get-primary-addr-by-name {{ primary_name }}
      retries: 5
      delay: 3
      until: newprimary.stdout != oldprimary.stdout
